//Prob #2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let normalFibonacci = (num) => {
  let arr = [];
    for (let i = 0; i < num; i++){
      if (arr.length > 2) {
        let last_number = arr[arr.length - 1];
        let second_to_last_number = arr[arr.length - 2];
        arr.push(last_number + second_to_last_number);
      } else {
        arr.push(i + 1);
      }
    }
    return arr;
}




const fibonacci = (num) => {
  if (num <= 1) {
    return 1;
  } else {
    return fibonacci(num - 1) + fibonacci(num + 2)
  }
}



const hammingDistance = (str1, str2) => {
  strOneArr = str1.split("");
  strTwoArr = str2.split("");
  let counter = 0;
  for (i = 0; i < strOneArr.length; i++){
    if (strOneArr[i] !== strTwoArr[i]) {
      counter += 1
    }
  }
  return counter;
}

hammingDistance("abcde", "bcdef") //5

//You are given a string and your task is to swap cases. In other words, convert all lowercase letters to uppercase letters and vice versa.

